### PR TITLE
Ops gulp create xhrenv

### PR DESCRIPTION
**Pull request by ahsu1230**
we can use gulp to create a dev webapp or a prod webapp depending on how we call gulp.

For example, by default, will build a debug webapp. Base server url is also pointing to localhost. etc.
```
$ gulp
```

```
$ gulp --release
```
will build the webapp with javascript minified, base server pointing to our real one. etc.

### CODE REVIEW

**Comment by ahsu1230** [comment]
This PR doesn't necessarily need to depend on this other PR:
https://github.com/bayeshack2016/vetafi/pull/46

but it made more sense to make this change after looking at some shortcomings of that other PR

**Comment by qwwqwwq** [comment]
Nice I like the approach, LGTM

**Comment by qwwqwwq** [comment]
Still think we dont need requestify though

**Comment by ahsu1230** [comment]
I used requestify for now because I was getting `access-control-allow-origin` problems from using the jquery `post` methods (ajax post do not work when the domain of your current site does not match the domain of your request). Requestify at least helps with all that complications - we should look for a workaround soon 👍

**Pull request merged**
